language: cpp
dist: trusty
sudo: required
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

before_script:
  - bash scripts/travis_before_script.sh

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source /opt/qt511/bin/qt511-env.sh; fi
  - cmake . -DCMAKE_INSTALL_PREFIX="/usr"
  - make

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash scripts/travis_deploy_qt.sh
  - bash ./upload.sh LCEdit*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
