language: cpp
dist: xenial
sudo: required
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

before_script:
  - bash scripts/travis_before_script.sh

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source /opt/qt511/bin/qt511-env.sh; fi
  - cmake .
  - make

after_success:
  - bash scripts/travis_deploy_qt.sh
