name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: Qt 5.12.2
      run: sudo add-apt-repository ppa:beineri/opt-qt-5.12.2-xenial
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install zlib1g-dev qt512base qt512tools qt512svg build-essential libgl1-mesa-dev -y
    - name: configure
      run: |
        mkdir build
        cd build
        source /opt/qt512/bin/qt512-env.sh && cmake -DCMAKE_INSTALL_PREFIX="/usr" -DCMAKE_BUILD_TYPE="Debug" -DLCEDIT_PLUGIN_DEPLOY_PATH='/usr/plugins' ..
    - name: make
      run: make
    - name: Install
      run: |
        mkdir appdir
        DESTDIR=appdir make install
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH
        chmod a+x ./linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/lcedit.desktop -appimage -bundle-non-qt-libs -no-strip -qmake=/opt/qt512/bin/qmake
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: LCEdit
        path: LCEdit-*-x86_64.AppImage
